In [20]:
import pandas as pd
import numpy as np
import pickle

In [21]:
matches = pickle.load(open('dataset_level1.pkl','rb'))

In [22]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'JJ Roy'}},
 {0.2: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Roy'}},
 {0.3: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'JJ Roy'}},
 {0.4: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'JJ Roy'}},
 {0.5: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'JJ Roy'}},
 {0.6: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JJ Roy'}},
 {0.7: {'non_striker': 'JJ Roy',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {1.1: {'non_striker': 'JJ Roy',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AD Hales'}},
 {1.2: {'non_striker': 'JJ Roy',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {1.3: {'non_striker': 'AD Hales',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Roy'}},
 {1.4: {'non_striker': 'AD Hales',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JJ Roy',
   'wicket': {'player_out': 'JJ Roy',
    'fielders': ['AJ Tye'],
    'kind': 'caught'}}},
 {1.5: {'non_striker': 'AD Hales',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {1.6: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AD Hales'}},
 {2.1: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DJ Malan'}},
 {2.2: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {2.3: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DJ Malan'}},
 {2.4: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'DJ Malan'}},
 {2.5: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'DJ Malan'}},
 {2.6: {'non_striker': 'AD Hales',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {3.1: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AD Hales'}},
 {3.2: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AD Hales'}},
 {3.3: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AD Hales'}},
 {3.4: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AD Hales'}},
 {3.5: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {3.6: {'non_striker': 'AD Hales',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {4.1: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'AD Hales'}},
 {4.2: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AD Hales'}},
 {4.3: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {4.4: {'non_striker': 'AD Hales',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {4.5: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {4.6: {'non_striker': 'AD Hales',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {5.1: {'non_striker': 'AD Hales',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {5.2: {'non_striker': 'AD Hales',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {5.3: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AD Hales'}},
 {5.4: {'non_striker': 'AD Hales',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {5.5: {'non_striker': 'AD Hales',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DJ Malan'}},
 {5.6: {'non_striker': 'AD Hales',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DJ Malan'}},
 {6.1: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AD Hales',
   'wicket': {'player_out': 'AD Hales', 'kind': 'caught and bowled'}}},
 {6.2: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'EJG Morgan'}},
 {6.3: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'EJG Morgan'}},
 {6.4: {'non_striker': 'EJG Morgan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'DJ Malan'}},
 {6.5: {'non_striker': 'EJG Morgan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {6.6: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'EJG Morgan'}},
 {7.1: {'non_striker': 'DJ Malan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'EJG Morgan'}},
 {7.2: {'non_striker': 'DJ Malan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'EJG Morgan'}},
 {7.3: {'non_striker': 'DJ Malan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'EJG Morgan'}},
 {7.4: {'non_striker': 'DJ Malan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'EJG Morgan'}},
 {7.5: {'non_striker': 'DJ Malan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'EJG Morgan'}},
 {7.6: {'non_striker': 'EJG Morgan',
   'bowler': 'TM Head',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {8.1: {'non_striker': 'EJG Morgan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {8.2: {'non_striker': 'EJG Morgan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'DJ Malan'}},
 {8.3: {'non_striker': 'EJG Morgan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'legbyes': 1},
   'batsman': 'DJ Malan'}},
 {8.4: {'non_striker': 'DJ Malan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'EJG Morgan'}},
 {8.5: {'non_striker': 'DJ Malan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'EJG Morgan'}},
 {8.6: {'non_striker': 'EJG Morgan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {8.7: {'non_striker': 'EJG Morgan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'DJ Malan'}},
 {9.1: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'EJG Morgan'}},
 {9.2: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'EJG Morgan'}},
 {9.3: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'EJG Morgan'}},
 {9.4: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'EJG Morgan',
   'wicket': {'player_out': 'EJG Morgan',
    'fielders': ['DA Warner'],
    'kind': 'caught'}}},
 {9.5: {'non_striker': 'JC Buttler',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {9.6: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JC Buttler'}},
 {10.1: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JC Buttler'}},
 {10.2: {'non_striker': 'JC Buttler',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {10.3: {'non_striker': 'JC Buttler',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {10.4: {'non_striker': 'JC Buttler',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {10.5: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JC Buttler'}},
 {10.6: {'non_striker': 'JC Buttler',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'DJ Malan'}},
 {11.1: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JC Buttler'}},
 {11.2: {'non_striker': 'JC Buttler',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {11.3: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JC Buttler'}},
 {11.4: {'non_striker': 'JC Buttler',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {11.5: {'non_striker': 'JC Buttler',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {11.6: {'non_striker': 'DJ Malan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JC Buttler'}},
 {12.1: {'non_striker': 'JC Buttler',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {12.2: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'JC Buttler'}},
 {12.3: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JC Buttler',
   'wicket': {'player_out': 'JC Buttler',
    'fielders': ['GJ Maxwell'],
    'kind': 'caught'}}},
 {12.4: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'SW Billings'}},
 {12.5: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SW Billings'}},
 {12.6: {'non_striker': 'SW Billings',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'DJ Malan'}},
 {12.7: {'non_striker': 'SW Billings',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {12.8: {'non_striker': 'DJ Malan',
   'bowler': 'MP Stoinis',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SW Billings'}},
 {13.1: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'SW Billings'}},
 {13.2: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SW Billings'}},
 {13.3: {'non_striker': 'SW Billings',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {13.4: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'SW Billings'}},
 {13.5: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'SW Billings'}},
 {13.6: {'non_striker': 'DJ Malan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SW Billings'}},
 {14.1: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'SW Billings',
   'wicket': {'player_out': 'SW Billings', 'kind': 'caught and bowled'}}},
 {14.2: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Willey'}},
 {14.3: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Willey'}},
 {14.4: {'non_striker': 'DJ Willey',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Malan'}},
 {14.5: {'non_striker': 'DJ Malan',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Willey'}},
 {14.6: {'non_striker': 'DJ Willey',
   'bowler': 'AC Agar',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan'}},
 {15.1: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Willey'}},
 {15.2: {'non_striker': 'DJ Malan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'DJ Willey'}},
 {15.3: {'non_striker': 'DJ Willey',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Malan',
   'wicket': {'player_out': 'DJ Malan',
    'fielders': ['AJ Tye'],
    'kind': 'caught'}}},
 {15.4: {'non_striker': 'CJ Jordan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'DJ Willey',
   'wicket': {'player_out': 'DJ Willey',
    'fielders': ['AT Carey'],
    'kind': 'stumped'}}},
 {15.5: {'non_striker': 'CJ Jordan',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AU Rashid'}},
 {15.6: {'non_striker': 'AU Rashid',
   'bowler': 'GJ Maxwell',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CJ Jordan'}},
 {16.1: {'non_striker': 'CJ Jordan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AU Rashid'}},
 {16.2: {'non_striker': 'CJ Jordan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AU Rashid'}},
 {16.3: {'non_striker': 'CJ Jordan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AU Rashid',
   'wicket': {'player_out': 'AU Rashid',
    'fielders': ['MP Stoinis'],
    'kind': 'caught'}}},
 {16.4: {'non_striker': 'TK Curran',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'CJ Jordan'}},
 {16.5: {'non_striker': 'TK Curran',
   'bowler': 'B Stanlake',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'legbyes': 1},
   'batsman': 'CJ Jordan'}},
 {16.6: {'non_striker': 'CJ Jordan',
   'bowler': 'B Stanlake',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'TK Curran'}},
 {17.1: {'non_striker': 'TK Curran',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {17.2: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'TK Curran',
   'wicket': {'player_out': 'TK Curran',
    'fielders': ['DA Warner'],
    'kind': 'caught'}}},
 {17.3: {'non_striker': 'MA Wood',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {17.4: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MA Wood'}},
 {17.5: {'non_striker': 'MA Wood',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {17.6: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MA Wood'}},
 {18.1: {'non_striker': 'MA Wood',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {18.2: {'non_striker': 'CJ Jordan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MA Wood'}},
 {18.3: {'non_striker': 'CJ Jordan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MA Wood'}},
 {18.4: {'non_striker': 'CJ Jordan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MA Wood'}},
 {18.5: {'non_striker': 'MA Wood',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {18.6: {'non_striker': 'CJ Jordan',
   'bowler': 'KW Richardson',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MA Wood'}},
 {19.1: {'non_striker': 'MA Wood',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'CJ Jordan'}},
 {19.2: {'non_striker': 'MA Wood',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CJ Jordan'}},
 {19.3: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MA Wood'}},
 {19.4: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'MA Wood'}},
 {19.5: {'non_striker': 'CJ Jordan',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MA Wood'}},
 {19.6: {'non_striker': 'MA Wood',
   'bowler': 'AJ Tye',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CJ Jordan'}}]

In [23]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

In [24]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[England, Australia]",England,0.1,JJ Roy,B Stanlake,2,0,Hobart,Bellerive Oval
1,2,"[England, Australia]",England,0.2,JJ Roy,B Stanlake,0,0,Hobart,Bellerive Oval
2,2,"[England, Australia]",England,0.3,JJ Roy,B Stanlake,1,0,Hobart,Bellerive Oval
3,2,"[England, Australia]",England,0.4,JJ Roy,B Stanlake,4,0,Hobart,Bellerive Oval
4,2,"[England, Australia]",England,0.5,JJ Roy,B Stanlake,2,0,Hobart,Bellerive Oval
...,...,...,...,...,...,...,...,...,...,...
156507,1305,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium
156508,1305,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium
156509,1305,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium
156510,1305,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium
156511,1305,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium

In [25]:

def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [26]:

delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [27]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [28]:
delivery_df.drop(columns=['teams'],inplace=True)

In [29]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [30]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,England,0.1,JJ Roy,B Stanlake,2,0,Hobart,Bellerive Oval,Australia
1,2,England,0.2,JJ Roy,B Stanlake,0,0,Hobart,Bellerive Oval,Australia
2,2,England,0.3,JJ Roy,B Stanlake,1,0,Hobart,Bellerive Oval,Australia
3,2,England,0.4,JJ Roy,B Stanlake,4,0,Hobart,Bellerive Oval,Australia
4,2,England,0.5,JJ Roy,B Stanlake,2,0,Hobart,Bellerive Oval,Australia
...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
156508,1305,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
156509,1305,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
156510,1305,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
156511,1305,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [31]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [32]:

output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,England,Australia,0.1,2,0,Hobart,Bellerive Oval
1,2,England,Australia,0.2,0,0,Hobart,Bellerive Oval
2,2,England,Australia,0.3,1,0,Hobart,Bellerive Oval
3,2,England,Australia,0.4,4,0,Hobart,Bellerive Oval
4,2,England,Australia,0.5,2,0,Hobart,Bellerive Oval
...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [33]:
pickle.dump(output,open('dataset_level2.pkl','wb'))